#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TICKET_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../../../.." && pwd)"
OUT_PATH="${TICKET_DIR}/various/01-host-build-surface-audit.md"

cd "${REPO_ROOT}"

HOST_SCRIPTS="$(
  node <<'EOF'
const fs = require('node:fs');
const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
const keys = [
  'launcher:frontend:build',
  'launcher:ui:sync',
  'launcher:binary:build',
  'launcher:smoke',
];
for (const key of keys) {
  console.log(`- \`${key}\`: \`${pkg.scripts[key]}\``);
}
EOF
)"

DOCKER_FILES="$(find . -maxdepth 3 \( -name 'Dockerfile' -o -name '.dockerignore' \) | sort || true)"
if [[ -z "${DOCKER_FILES}" ]]; then
  DOCKER_FILES="(none found under repo root depth 3)"
fi

K8S_FILES="$(find deploy .github -maxdepth 4 \( -iname '*k8s*' -o -iname '*helm*' -o -iname '*kustom*' -o -name '*deploy*' \) 2>/dev/null | sort || true)"
if [[ -z "${K8S_FILES}" ]]; then
  K8S_FILES="(no deploy/k8s, Helm, or Kustomize files found)"
fi

cat > "${OUT_PATH}" <<EOF
# Host Build Surface Audit

Generated by:

- \`ttmp/2026/03/29/DEPLOY-001--k3s-host-deployment-federated-modules-and-github-ci-cd/scripts/01-audit-host-build-surface.sh\`

## Summary

The current \`wesen-os\` launcher is already packaged as a combined frontend-plus-Go-binary runtime:

- \`apps/os-launcher\` builds the SPA
- \`scripts/launcher-ui-sync.sh\` copies built assets into \`pkg/launcherui/dist\`
- \`pkg/launcherui/handler.go\` embeds and serves \`dist\`
- \`scripts/build-wesen-os-launcher.sh\` builds \`./cmd/wesen-os-launcher\`

That means the first production container should likely package the combined launcher binary rather than split the host into separate webserver/frontend pieces.

## Root Build Scripts

${HOST_SCRIPTS}

## Key Packaging Files

- \`package.json\`
- \`scripts/build-wesen-os-launcher.sh\`
- \`scripts/launcher-ui-sync.sh\`
- \`scripts/smoke-wesen-os-launcher.sh\`
- \`cmd/wesen-os-launcher/main.go\`
- \`pkg/launcherui/handler.go\`
- \`pkg/launcherui/dist/.embedkeep\`

## Existing Docker/K8s Artifacts

### Docker-ish files

\`\`\`text
${DOCKER_FILES}
\`\`\`

### Deployment-ish files

\`\`\`text
${K8S_FILES}
\`\`\`

## build-wesen-os-launcher.sh

\`\`\`bash
$(sed -n '1,160p' scripts/build-wesen-os-launcher.sh)
\`\`\`

## launcher-ui-sync.sh

\`\`\`bash
$(sed -n '1,160p' scripts/launcher-ui-sync.sh)
\`\`\`

## launcherui embed handler

\`\`\`go
$(sed -n '1,160p' pkg/launcherui/handler.go)
\`\`\`

## Main launcher embedding and serve points

\`\`\`go
$(sed -n '1,120p' cmd/wesen-os-launcher/main.go)
\`\`\`

## Findings

- The binary packaging chain is already explicit and reusable.
- The frontend embed path is \`pkg/launcherui/dist\`.
- The Go embed directive is \`//go:embed all:dist\`.
- The launcher serves the SPA via \`launcherui.Handler()\`.
- The current repo already has a meaningful smoke test that exercises backend routes and the root HTML shell.
- No first-class Docker/K3s deployment artifacts exist yet in the root repo.

## Recommended Next Task

Add:

- a production \`Dockerfile\`
- a \`.dockerignore\`
- a small image build smoke path that reuses the existing binary packaging chain
EOF

echo "wrote ${OUT_PATH}"
