#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TICKET_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../../../.." && pwd)"
OUT_PATH="${TICKET_DIR}/various/02-repo-local-go-work-check.md"

cd "${REPO_ROOT}"

OUTSIDE_PATHS="$(rg -n '^\s+\.\./' go.work || true)"
if [[ -z "${OUTSIDE_PATHS}" ]]; then
  OUTSIDE_PATHS="(none)"
fi

GO_WORK_SECTION="$(sed -n '1,120p' go.work)"
SUBMODULES_SECTION="$(sed -n '1,260p' .gitmodules)"

BUILD_RESULT="PASS"
BUILD_LOG="$(mktemp)"
if ! go build -o /tmp/wesen-os-launcher-repo-local ./cmd/wesen-os-launcher >"${BUILD_LOG}" 2>&1; then
  BUILD_RESULT="FAIL"
fi

cat > "${OUT_PATH}" <<EOF
# Repo-Local Go Workspace Check

Generated by:

- \`ttmp/2026/03/29/DEPLOY-001--k3s-host-deployment-federated-modules-and-github-ci-cd/scripts/02-check-repo-local-go-work.sh\`

## Outside-Repo Paths In go.work

\`\`\`text
${OUTSIDE_PATHS}
\`\`\`

## go.work

\`\`\`go
${GO_WORK_SECTION}
\`\`\`

## .gitmodules

\`\`\`ini
${SUBMODULES_SECTION}
\`\`\`

## Launcher Build Result

- \`${BUILD_RESULT}\`

## Build Log

\`\`\`text
$(sed -n '1,200p' "${BUILD_LOG}")
\`\`\`
EOF

rm -f "${BUILD_LOG}"
echo "wrote ${OUT_PATH}"

if [[ "${BUILD_RESULT}" != "PASS" ]]; then
  echo "repo-local go work check failed" >&2
  exit 1
fi
