#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TICKET_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../../../.." && pwd)"
OUT_PATH="${TICKET_DIR}/various/03-host-image-build-check.md"

IMAGE_TAG="${IMAGE_TAG:-wesen-os:deploy-001}"

cd "${REPO_ROOT}"

BUILD_LOG="$(mktemp)"

if docker build -f Dockerfile -t "${IMAGE_TAG}" . >"${BUILD_LOG}" 2>&1; then
  BUILD_RESULT="PASS"
else
  BUILD_RESULT="FAIL"
fi

IMAGE_INFO="$(docker image inspect "${IMAGE_TAG}" --format '{{.Id}} {{.Size}}' 2>/dev/null || true)"
if [[ -z "${IMAGE_INFO}" ]]; then
  IMAGE_INFO="(image not present)"
fi

cat > "${OUT_PATH}" <<EOF
# Host Image Build Check

Generated by:

- \`ttmp/2026/03/29/DEPLOY-001--k3s-host-deployment-federated-modules-and-github-ci-cd/scripts/03-build-host-image.sh\`

## Build Result

- \`${BUILD_RESULT}\`

## Image Tag

- \`${IMAGE_TAG}\`

## Image Info

\`\`\`text
${IMAGE_INFO}
\`\`\`

## Build Log

\`\`\`text
$(sed -n '1,240p' "${BUILD_LOG}")
\`\`\`
EOF

rm -f "${BUILD_LOG}"
echo "wrote ${OUT_PATH}"

if [[ "${BUILD_RESULT}" != "PASS" ]]; then
  exit 1
fi

echo "built ${IMAGE_TAG}"
