#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TICKET_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_PATH="${TICKET_DIR}/various/04-host-image-smoke-check.md"

IMAGE_TAG="${IMAGE_TAG:-wesen-os:deploy-001}"
PORT="${PORT:-18091}"
CONTAINER_NAME="${CONTAINER_NAME:-wesen-os-deploy-001-smoke}"
BASE_URL="http://127.0.0.1:${PORT}"
PROFILE_FILE="$(mktemp "${TMPDIR:-/tmp}/wesen-os-profiles.XXXXXX.yaml")"
WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/wesen-os-image-smoke.XXXXXX")"
ROOT_HTML="${WORK_DIR}/root.html"
APPS_JSON="${WORK_DIR}/apps.json"

cat > "${PROFILE_FILE}" <<'YAML'
slug: smoke
profiles:
  default:
    slug: default
    runtime:
      step_settings_patch:
        ai-chat:
          ai-engine: gpt-4.1-mini
YAML
chmod 644 "${PROFILE_FILE}"

cleanup() {
  docker rm -f "${CONTAINER_NAME}" >/dev/null 2>&1 || true
  rm -f "${PROFILE_FILE}" >/dev/null 2>&1 || true
  rm -rf "${WORK_DIR}" >/dev/null 2>&1 || true
}
trap cleanup EXIT

docker rm -f "${CONTAINER_NAME}" >/dev/null 2>&1 || true
docker run -d \
  --name "${CONTAINER_NAME}" \
  -p "127.0.0.1:${PORT}:8091" \
  -v "${PROFILE_FILE}:/tmp/profiles.runtime.yaml:ro" \
  "${IMAGE_TAG}" \
  --addr=:8091 \
  --arc-enabled=false \
  --profile default \
  --profile-registries /tmp/profiles.runtime.yaml >/dev/null

READY=0
ROOT_STATUS=""
APPS_STATUS=""
for _ in $(seq 1 200); do
  ROOT_STATUS="$(curl -sS -o "${ROOT_HTML}" -w "%{http_code}" "${BASE_URL}/" 2>/dev/null || true)"
  APPS_STATUS="$(curl -sS -o "${APPS_JSON}" -w "%{http_code}" "${BASE_URL}/api/os/apps" 2>/dev/null || true)"
  if [[ "${ROOT_STATUS}" == "200" && "${APPS_STATUS}" == "200" ]]; then
    READY=1
    break
  fi
  if [[ "$(docker inspect -f '{{.State.Running}}' "${CONTAINER_NAME}" 2>/dev/null || true)" == "false" ]]; then
    break
  fi
  sleep 0.2
done

RESULT="PASS"
MESSAGE="container served root and /api/os/apps"

if [[ "${READY}" != "1" ]]; then
  RESULT="FAIL"
  MESSAGE="container did not become ready"
fi

if [[ "${RESULT}" == "PASS" ]] && ! grep -qi '<div id="root"' "${ROOT_HTML}"; then
  RESULT="FAIL"
  MESSAGE="root HTML missing root mount"
fi

if [[ "${RESULT}" == "PASS" ]] && ! grep -q '"app_id":"inventory"' "${APPS_JSON}"; then
  RESULT="FAIL"
  MESSAGE="/api/os/apps missing inventory app"
fi

if [[ "${RESULT}" == "PASS" ]] && ! grep -q '"app_id":"sqlite"' "${APPS_JSON}"; then
  RESULT="FAIL"
  MESSAGE="/api/os/apps missing sqlite app"
fi

CONTAINER_LOG="$(docker logs "${CONTAINER_NAME}" 2>&1 || true)"
CONTAINER_STATE="$(docker inspect -f '{{.State.Status}}' "${CONTAINER_NAME}" 2>/dev/null || true)"
CONTAINER_EXIT_CODE="$(docker inspect -f '{{.State.ExitCode}}' "${CONTAINER_NAME}" 2>/dev/null || true)"

cat > "${OUT_PATH}" <<EOF
# Host Image Smoke Check

Generated by:

- \`ttmp/2026/03/29/DEPLOY-001--k3s-host-deployment-federated-modules-and-github-ci-cd/scripts/04-smoke-host-image.sh\`

## Result

- \`${RESULT}\`
- \`${MESSAGE}\`

## Image Tag

- \`${IMAGE_TAG}\`

## Root Status

- \`${ROOT_STATUS}\`

## Apps Status

- \`${APPS_STATUS}\`

## Container State

- status: \`${CONTAINER_STATE}\`
- exit_code: \`${CONTAINER_EXIT_CODE}\`

## Root HTML

\`\`\`html
$(sed -n '1,80p' "${ROOT_HTML}" 2>/dev/null || true)
\`\`\`

## /api/os/apps

\`\`\`json
$(sed -n '1,120p' "${APPS_JSON}" 2>/dev/null || true)
\`\`\`

## Container Logs

\`\`\`text
${CONTAINER_LOG}
\`\`\`
EOF

echo "wrote ${OUT_PATH}"

if [[ "${RESULT}" != "PASS" ]]; then
  exit 1
fi
