#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TICKET_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${TICKET_DIR}/../../../../.." && pwd)"
OUT_PATH="${TICKET_DIR}/various/05-launcher-build-determinism-check.md"
WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/launcher-determinism.XXXXXX")"

DIST1="${WORK_DIR}/dist-1"
DIST2="${WORK_DIR}/dist-2"
HASH1="${WORK_DIR}/hashes-1.txt"
HASH2="${WORK_DIR}/hashes-2.txt"
LOG1="${WORK_DIR}/build-1.log"
LOG2="${WORK_DIR}/build-2.log"

cleanup() {
  rm -rf "${WORK_DIR}" >/dev/null 2>&1 || true
}
trap cleanup EXIT

run_build() {
  local dist_target="$1"
  local hash_target="$2"
  local log_target="$3"

  rm -rf "${REPO_ROOT}/apps/os-launcher/dist"
  (
    cd "${REPO_ROOT}/apps/os-launcher"
    npm run build
  ) >"${log_target}" 2>&1

  cp -R "${REPO_ROOT}/apps/os-launcher/dist" "${dist_target}"
  (
    cd "${dist_target}"
    find . -type f | LC_ALL=C sort | while read -r path; do
      shasum -a 256 "${path}"
    done
  ) >"${hash_target}"
}

run_build "${DIST1}" "${HASH1}" "${LOG1}"
run_build "${DIST2}" "${HASH2}" "${LOG2}"

RESULT="PASS"
MESSAGE="two clean launcher builds produced identical relative-file hashes"
DIFF_OUTPUT=""

if ! DIFF_OUTPUT="$(diff -u "${HASH1}" "${HASH2}" 2>&1)"; then
  RESULT="FAIL"
  MESSAGE="launcher dist output changed across repeated clean builds"
fi

cat > "${OUT_PATH}" <<EOF
# Launcher Build Determinism Check

Generated by:

- \`ttmp/2026/03/29/DEPLOY-001--k3s-host-deployment-federated-modules-and-github-ci-cd/scripts/05-check-launcher-build-determinism.sh\`

## Result

- \`${RESULT}\`
- \`${MESSAGE}\`

## Build 1 Hashes

\`\`\`text
$(sed -n '1,120p' "${HASH1}")
\`\`\`

## Build 2 Hashes

\`\`\`text
$(sed -n '1,120p' "${HASH2}")
\`\`\`

## Hash Diff

\`\`\`diff
${DIFF_OUTPUT}
\`\`\`

## Build 1 Log Tail

\`\`\`text
$(tail -n 60 "${LOG1}" 2>/dev/null || true)
\`\`\`

## Build 2 Log Tail

\`\`\`text
$(tail -n 60 "${LOG2}" 2>/dev/null || true)
\`\`\`
EOF

echo "wrote ${OUT_PATH}"

if [[ "${RESULT}" != "PASS" ]]; then
  exit 1
fi
