#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TICKET_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${TICKET_DIR}/../../../../.." && pwd)"
OUT_PATH="${TICKET_DIR}/various/06-host-image-tagging-plan.md"

cd "${REPO_ROOT}"

REMOTE_URL="$(git remote get-url origin)"
REPO_SLUG="${GITHUB_REPOSITORY:-}"
if [[ -z "${REPO_SLUG}" ]]; then
  case "${REMOTE_URL}" in
    git@github.com:*)
      REPO_SLUG="${REMOTE_URL#git@github.com:}"
      ;;
    https://github.com/*)
      REPO_SLUG="${REMOTE_URL#https://github.com/}"
      ;;
    *)
      echo "unsupported origin remote: ${REMOTE_URL}" >&2
      exit 1
      ;;
  esac
  REPO_SLUG="${REPO_SLUG%.git}"
fi

OWNER="${REPO_SLUG%%/*}"
REPO_NAME="${REPO_SLUG##*/}"
IMAGE_REPO="ghcr.io/${OWNER}/${REPO_NAME}"
FULL_SHA="${GITHUB_SHA:-$(git rev-parse HEAD)}"
SHORT_SHA="$(printf '%s' "${FULL_SHA}" | cut -c1-12)"
BRANCH_NAME="${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}"
BRANCH_TAG="$(printf '%s' "${BRANCH_NAME}" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9._-]+/-/g; s/^-+//; s/-+$//')"

PRIMARY_IMMUTABLE_REF="${IMAGE_REPO}:sha-${FULL_SHA}"
SHORT_IMMUTABLE_REF="${IMAGE_REPO}:sha-${SHORT_SHA}"
MUTABLE_REF=""
if [[ "${BRANCH_NAME}" == "main" ]]; then
  MUTABLE_REF="${IMAGE_REPO}:main"
fi

cat > "${OUT_PATH}" <<EOF
# Host Image Tagging Plan

Generated by:

- \`ttmp/2026/03/29/DEPLOY-001--k3s-host-deployment-federated-modules-and-github-ci-cd/scripts/06-resolve-host-image-tags.sh\`

## Repository Inputs

- origin: \`${REMOTE_URL}\`
- repo_slug: \`${REPO_SLUG}\`
- branch: \`${BRANCH_NAME}\`
- git_sha: \`${FULL_SHA}\`

## Decision

- canonical image repository: \`${IMAGE_REPO}\`
- immutable publish tag: \`${PRIMARY_IMMUTABLE_REF}\`
- short immutable convenience tag: \`${SHORT_IMMUTABLE_REF}\`
- mutable branch tag:
  - $(if [[ -n "${MUTABLE_REF}" ]]; then printf '\`%s\` (only for main branch publishes)' "${MUTABLE_REF}"; else printf 'none (non-main branch)'; fi)
- deployment manifests should pin image digests rather than mutable tags

## Proposed OCI Labels

- \`org.opencontainers.image.source=https://github.com/${REPO_SLUG}\`
- \`org.opencontainers.image.revision=${FULL_SHA}\`
- \`org.opencontainers.image.title=${REPO_NAME}\`

## Notes

- The immutable tag should always exist for traceability and rollback.
- The short SHA tag is optional but convenient for humans reading registry listings.
- The mutable \`main\` tag should exist only for the default branch so staging or ad hoc branches do not overwrite a shared moving reference.
- Kubernetes manifests should ultimately deploy \`${IMAGE_REPO}@sha256:...\` after the GHCR workflow resolves the pushed digest.
- Non-main branches can still publish preview images if needed, but they should use explicit branch-scoped tags rather than reusing \`main\`.

## Suggested Preview Tag

- \`${IMAGE_REPO}:branch-${BRANCH_TAG}-${SHORT_SHA}\`
EOF

echo "wrote ${OUT_PATH}"
