#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TICKET_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${TICKET_DIR}/../../../../.." && pwd)"
OUT_PATH="${TICKET_DIR}/various/07-host-runtime-config-audit.md"
WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/host-runtime-config.XXXXXX")"
HELP_PATH="${WORK_DIR}/launcher-help.txt"
ENV_GREP_PATH="${WORK_DIR}/env-grep.txt"

cleanup() {
  rm -rf "${WORK_DIR}" >/dev/null 2>&1 || true
}
trap cleanup EXIT

(
  cd "${REPO_ROOT}"
  go run ./cmd/wesen-os-launcher wesen-os-launcher --help
) > "${HELP_PATH}"

(
  cd "${REPO_ROOT}"
  rg -n "os\\.Getenv\\(|LookupEnv\\(|PINOCCHIO_PROFILE|PINOCCHIO_PROFILE_REGISTRIES|INVENTORY_CHAT_BACKEND|GO_GO_OS_FRONTEND_RESOLUTION" \
    cmd pkg apps/os-launcher scripts -g '!**/dist/**'
) > "${ENV_GREP_PATH}"

PROFILE_FLAGS="$(rg -n -- '--profile|--profile-registries' "${HELP_PATH}" || true)"
SERVER_FLAGS="$(rg -n -- '--addr|--root|--required-apps|--inventory-db|--sqlite-db|--timeline-dsn|--turns-dsn|--arc-enabled' "${HELP_PATH}" || true)"
DEBUG_FLAGS="$(rg -n -- 'PINOCCHIO_PROFILE_REGISTRIES|PINOCCHIO_PROFILE|PINOCCHIO_WEBCHAT_DEBUG|INVENTORY_CHAT_BACKEND|GO_GO_OS_FRONTEND_RESOLUTION' "${ENV_GREP_PATH}" || true)"

cat > "${OUT_PATH}" <<EOF
# Host Runtime Config Audit

Generated by:

- \`ttmp/2026/03/29/DEPLOY-001--k3s-host-deployment-federated-modules-and-github-ci-cd/scripts/07-audit-host-runtime-config.sh\`

## Core Conclusion

- The host does **not** require a large set of direct process environment variables to boot.
- The main required runtime input is a profile registry source:
  - via \`--profile-registries\`
  - or via \`PINOCCHIO_PROFILE_REGISTRIES\` through the profile bootstrap layer
- For the first production image, ARC should be disabled unless the runtime image is deliberately extended with ARC dependencies:
  - \`--arc-enabled=false\`

## Required Runtime Inputs For First Container

1. HTTP listen configuration
   - flag: \`--addr\`
   - current image default: \`:8091\`
2. Profile registry source
   - flag: \`--profile-registries\`
   - env fallback: \`PINOCCHIO_PROFILE_REGISTRIES\`
3. Selected profile
   - flag: \`--profile\`
   - env fallback: \`PINOCCHIO_PROFILE\`
4. ARC disablement for the minimal first image
   - flag: \`--arc-enabled=false\`

## Strongly Recommended Container Defaults

- \`--addr=:8091\`
- \`--arc-enabled=false\`
- mounted profile registry file, for example:
  - \`--profile default --profile-registries /config/profiles.runtime.yaml\`

## Important Optional Runtime Flags

- persistence / domain data:
  - \`--inventory-db\`
  - \`--sqlite-db\`
  - \`--timeline-dsn\`
  - \`--turns-dsn\`
- startup policy:
  - \`--required-apps\`
  - \`--legacy-aliases\`
- routing:
  - \`--root\`
- ARC tuning when ARC is deliberately enabled:
  - \`--arc-driver\`
  - \`--arc-runtime-mode\`
  - \`--arc-repo-root\`
  - \`--arc-startup-timeout-seconds\`
  - \`--arc-request-timeout-seconds\`

## Direct Environment Variables Observed In Repo Code

- \`PINOCCHIO_WEBCHAT_DEBUG\`
  - enables debug routes for webchat servers
- \`PINOCCHIO_PROFILE\`
  - used through profile bootstrap fallback/selection flow
- \`PINOCCHIO_PROFILE_REGISTRIES\`
  - used through profile bootstrap fallback/selection flow

## Frontend / Dev-Only Environment Variables Observed

- \`INVENTORY_CHAT_BACKEND\`
  - used by \`apps/os-launcher/vite.config.ts\` for local Vite proxying
- \`GO_GO_OS_FRONTEND_RESOLUTION\`
  - used to switch launcher frontend resolution mode between workspace and published packages

## Deployment Interpretation

- In Kubernetes, the launcher should preferably get its profile registry from a mounted config file and explicit flags, not from hidden workstation defaults.
- The first production deployment can avoid ARC-specific runtime dependencies by forcing \`--arc-enabled=false\`.
- Database file paths can remain on local container storage for early smoke/staging work, but production persistence needs an explicit storage decision later.
- AI provider credentials and inference settings are surfaced mainly as Glazed/Clay flags and config inputs; this audit does not claim a complete env-variable contract for those providers.

## Relevant Help Excerpts

### Profile Flags

\`\`\`text
${PROFILE_FLAGS}
\`\`\`

### Server Flags

\`\`\`text
${SERVER_FLAGS}
\`\`\`

### Environment Grep

\`\`\`text
$(sed -n '1,200p' "${ENV_GREP_PATH}")
\`\`\`
EOF

echo "wrote ${OUT_PATH}"
