#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TICKET_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${TICKET_DIR}/../../../../.." && pwd)"
OUT_PATH="${TICKET_DIR}/various/08-host-publish-workflow-check.md"
WORKFLOW_PATH="${REPO_ROOT}/.github/workflows/publish-host-image.yml"

cd "${REPO_ROOT}"

yq eval '.' "${WORKFLOW_PATH}" >/dev/null

CHECKOUT_LINE="$(rg -n 'actions/checkout@' "${WORKFLOW_PATH}" || true)"
PNPM_LINE="$(rg -n 'pnpm/action-setup@' "${WORKFLOW_PATH}" || true)"
NODE_LINE="$(rg -n 'actions/setup-node@' "${WORKFLOW_PATH}" || true)"
LOGIN_LINE="$(rg -n 'docker/login-action@' "${WORKFLOW_PATH}" || true)"
META_LINE="$(rg -n 'docker/metadata-action@' "${WORKFLOW_PATH}" || true)"
BUILD_PUSH_LINE="$(rg -n 'docker/build-push-action@' "${WORKFLOW_PATH}" || true)"
SHA_TAG_LINE="$(rg -n 'type=sha,prefix=sha-' "${WORKFLOW_PATH}" || true)"
MAIN_TAG_LINE="$(rg -n 'type=raw,value=main' "${WORKFLOW_PATH}" || true)"

cat > "${OUT_PATH}" <<EOF
# Host Publish Workflow Check

Generated by:

- \`ttmp/2026/03/29/DEPLOY-001--k3s-host-deployment-federated-modules-and-github-ci-cd/scripts/08-check-host-publish-workflow.sh\`

## Result

- \`PASS\`
- \`publish-host-image.yml parsed as valid YAML and contains the expected GHCR publish steps\`

## Workflow Path

- \`.github/workflows/publish-host-image.yml\`

## Expected Action Anchors

- checkout:

\`\`\`text
${CHECKOUT_LINE}
\`\`\`

- pnpm setup:

\`\`\`text
${PNPM_LINE}
\`\`\`

- node setup:

\`\`\`text
${NODE_LINE}
\`\`\`

- GHCR login:

\`\`\`text
${LOGIN_LINE}
\`\`\`

- metadata extraction:

\`\`\`text
${META_LINE}
\`\`\`

- build and push:

\`\`\`text
${BUILD_PUSH_LINE}
\`\`\`

## Tag Policy Anchors

- immutable SHA tag:

\`\`\`text
${SHA_TAG_LINE}
\`\`\`

- mutable main tag:

\`\`\`text
${MAIN_TAG_LINE}
\`\`\`

## Workflow Excerpt

\`\`\`yaml
$(sed -n '1,220p' "${WORKFLOW_PATH}")
\`\`\`
EOF

echo "wrote ${OUT_PATH}"
