#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TICKET_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${TICKET_DIR}/../../../../.." && pwd)"
OUT_PATH="${TICKET_DIR}/various/09-k8s-host-manifest-render.md"
MANIFEST_DIR="${REPO_ROOT}/deploy/k8s/wesen-os"
WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/wesen-os-kustomize.XXXXXX")"
RENDERED_PATH="${WORK_DIR}/rendered.yaml"

cleanup() {
  rm -rf "${WORK_DIR}" >/dev/null 2>&1 || true
}
trap cleanup EXIT

kubectl kustomize "${MANIFEST_DIR}" > "${RENDERED_PATH}"

cat > "${OUT_PATH}" <<EOF
# K8s Host Manifest Render

Generated by:

- \`ttmp/2026/03/29/DEPLOY-001--k3s-host-deployment-federated-modules-and-github-ci-cd/scripts/09-render-k8s-host-manifests.sh\`

## Result

- \`PASS\`
- \`kubectl kustomize deploy/k8s/wesen-os rendered successfully\`

## Manifest Directory

- \`deploy/k8s/wesen-os\`

## Rendered Output

\`\`\`yaml
$(sed -n '1,260p' "${RENDERED_PATH}")
\`\`\`
EOF

echo "wrote ${OUT_PATH}"
