#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TICKET_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${TICKET_DIR}/../../../../.." && pwd)"
OUT_PATH="${TICKET_DIR}/various/10-k3s-deploy-workflow-check.md"
WORKFLOW_PATH="${REPO_ROOT}/.github/workflows/deploy-host-to-k3s.yml"

cd "${REPO_ROOT}"

yq eval '.' "${WORKFLOW_PATH}" >/dev/null

ENV_LINE="$(rg -n 'environment: staging' "${WORKFLOW_PATH}" || true)"
KUBECONFIG_LINE="$(rg -n 'KUBECONFIG_B64|\\.kube/config' "${WORKFLOW_PATH}" || true)"
APPLY_LINE="$(rg -n 'kubectl apply -k deploy/k8s/wesen-os' "${WORKFLOW_PATH}" || true)"
SET_IMAGE_LINE="$(rg -n 'kubectl -n wesen-os set image deployment/wesen-os' "${WORKFLOW_PATH}" || true)"
ROLLOUT_LINE="$(rg -n 'rollout status deployment/wesen-os' "${WORKFLOW_PATH}" || true)"

cat > "${OUT_PATH}" <<EOF
# K3s Deploy Workflow Check

Generated by:

- \`ttmp/2026/03/29/DEPLOY-001--k3s-host-deployment-federated-modules-and-github-ci-cd/scripts/10-check-k3s-deploy-workflow.sh\`

## Result

- \`PASS\`
- \`deploy-host-to-k3s.yml parsed as valid YAML and contains the expected staging deploy steps\`

## Workflow Path

- \`.github/workflows/deploy-host-to-k3s.yml\`

## Expected Anchors

- environment:

\`\`\`text
${ENV_LINE}
\`\`\`

- kubeconfig setup:

\`\`\`text
${KUBECONFIG_LINE}
\`\`\`

- apply manifests:

\`\`\`text
${APPLY_LINE}
\`\`\`

- pin image:

\`\`\`text
${SET_IMAGE_LINE}
\`\`\`

- rollout:

\`\`\`text
${ROLLOUT_LINE}
\`\`\`

## Workflow Excerpt

\`\`\`yaml
$(sed -n '1,220p' "${WORKFLOW_PATH}")
\`\`\`
EOF

echo "wrote ${OUT_PATH}"
