#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TICKET_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
K3S_REPO="/home/manuel/code/wesen/2026-03-27--hetzner-k3s"
PACKAGE_DIR="${K3S_REPO}/gitops/kustomize/wesen-os"
OUT_PATH="${TICKET_DIR}/various/11-hetzner-k3s-wesen-os-package-render.md"
WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/wesen-os-k3s-package.XXXXXX")"
RENDERED_PATH="${WORK_DIR}/rendered.yaml"

cleanup() {
  rm -rf "${WORK_DIR}" >/dev/null 2>&1 || true
}
trap cleanup EXIT

kubectl kustomize "${PACKAGE_DIR}" > "${RENDERED_PATH}"

cat > "${OUT_PATH}" <<EOF
# Hetzner K3s wesen-os Package Render

Generated by:

- \`ttmp/2026/03/29/DEPLOY-001--k3s-host-deployment-federated-modules-and-github-ci-cd/scripts/11-render-hetzner-k3s-wesen-os-package.sh\`

## Result

- \`PASS\`
- \`kubectl kustomize gitops/kustomize/wesen-os rendered successfully\`

## Package Directory

- \`${PACKAGE_DIR}\`

## Rendered Output

\`\`\`yaml
$(sed -n '1,260p' "${RENDERED_PATH}")
\`\`\`
EOF

echo "wrote ${OUT_PATH}"
