#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TICKET_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
APP_PATH="/home/manuel/code/wesen/2026-03-27--hetzner-k3s/gitops/applications/wesen-os.yaml"
OUT_PATH="${TICKET_DIR}/various/12-hetzner-k3s-wesen-os-application-check.md"

yq eval '.' "${APP_PATH}" >/dev/null

NAME="$(yq eval '.metadata.name' "${APP_PATH}")"
NAMESPACE="$(yq eval '.spec.destination.namespace' "${APP_PATH}")"
SOURCE_PATH="$(yq eval '.spec.source.path' "${APP_PATH}")"
REPO_URL="$(yq eval '.spec.source.repoURL' "${APP_PATH}")"
TARGET_REV="$(yq eval '.spec.source.targetRevision' "${APP_PATH}")"

cat > "${OUT_PATH}" <<EOF
# Hetzner K3s wesen-os Application Check

Generated by:

- \`ttmp/2026/03/29/DEPLOY-001--k3s-host-deployment-federated-modules-and-github-ci-cd/scripts/12-check-hetzner-k3s-wesen-os-application.sh\`

## Result

- \`PASS\`
- \`wesen-os Argo CD Application parsed as valid YAML and points at the expected Kustomize package\`

## Key Fields

- name: \`${NAME}\`
- destination namespace: \`${NAMESPACE}\`
- source repo: \`${REPO_URL}\`
- source revision: \`${TARGET_REV}\`
- source path: \`${SOURCE_PATH}\`

## Manifest

\`\`\`yaml
$(sed -n '1,220p' "${APP_PATH}")
\`\`\`
EOF

echo "wrote ${OUT_PATH}"
