#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TICKET_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_PATH="${TICKET_DIR}/various/13-wesen-os-repo-visibility-and-ghcr-path.md"

REPO_JSON="$(gh repo view wesen/wesen-os --json visibility,isPrivate,url,nameWithOwner)"
VISIBILITY="$(printf '%s' "${REPO_JSON}" | jq -r '.visibility')"
IS_PRIVATE="$(printf '%s' "${REPO_JSON}" | jq -r '.isPrivate')"
REPO_URL="$(printf '%s' "${REPO_JSON}" | jq -r '.url')"

PATH_DECISION="public GHCR image path for first rollout"
if [[ "${VISIBILITY}" != "PUBLIC" || "${IS_PRIVATE}" != "false" ]]; then
  PATH_DECISION="private-image path required"
fi

cat > "${OUT_PATH}" <<EOF
# wesen-os Repo Visibility And GHCR Path

Generated by:

- \`ttmp/2026/03/29/DEPLOY-001--k3s-host-deployment-federated-modules-and-github-ci-cd/scripts/13-check-wesen-os-repo-visibility.sh\`

## Repository Visibility

- repo: \`wesen/wesen-os\`
- url: \`${REPO_URL}\`
- visibility: \`${VISIBILITY}\`
- is_private: \`${IS_PRIVATE}\`

## Decision

- \`${PATH_DECISION}\`

## Notes

- A public source repository makes the public-GHCR path the right default for the first deployment model.
- This does **not** prove the GHCR package is already publicly pullable.
- After the first real image publish, we still need to verify the image can be pulled anonymously or from the cluster without additional credentials.
- If GHCR package visibility does not match the intended public path, the next fallback is to add the cluster-side image pull secret pattern in the Hetzner repo.

## Raw Output

\`\`\`json
${REPO_JSON}
\`\`\`
EOF

echo "wrote ${OUT_PATH}"
