apiVersion: v1
kind: ConfigMap
metadata:
  name: wesen-os-config
data:
  profiles.runtime.yaml: |
    slug: cluster-default
    profiles:
      default:
        slug: default
        runtime:
          step_settings_patch:
            ai-chat:
              ai-engine: gpt-4.1-mini
  federation.registry.json: |
    {
      "version": 1,
      "remotes": [
        {
          "remoteId": "inventory",
          "mode": "remote-manifest",
          "enabled": true,
          "manifestUrl": "https://scapegoat-federation-assets.fsn1.your-objectstorage.com/remotes/inventory/versions/sha-f69ca10/mf-manifest.json"
        }
      ]
    }
